routes/web.php
<?php

Route::get('/', function() {
	return redirect ('/login');
});

// Routes for admin --------
Route::get('/admin', 'PageAdminController@surat');

//Route::get('/admin/surat_tugas', 'PageAdminController@surat');

//Route::get('/admin/laporan', 'PageAdminController@laporan');

Route::get('/admin/rekapitulasi', 'PageAdminController@rekapitulasi');
	// Routes for content of rekapitulasi
	//Route::get('/admin/rekapitulasi/surat_tugas', 'PageAdminController@rekapitulasi_surat');
	Route::get('/admin/rekapitulasi/perjalanan', 'PageAdminController@rekapitulasi_perjalanan');
	//Route::get('/admin/rekapitulasi/keuangan', 'PageAdminController@rekapitulasi_keuangan');

Route::get('/admin/referensi', 'PageAdminController@referensi');

Route::resource('admin/referensi/pegawai', 'PenggunaController');
Route::resource('admin/surat_tugas', 'Surat_TugasController');
Route::resource('admin/laporan', 'LaporanController');
Route::resource('admin/rekapitulasi/surat_tugas', 'Rekap_SuratController');
Route::resource('admin/rekapitulasi/keuangan', 'Rekap_UangController');

// End routes for admin --------


// Routes for users --------
// Routes for paging
Route::get('/home', 'PageController@home');

//Route::get('/home/surat_tugas', 'PageController@surat');

//Route::get('/home/laporan', 'PageController@laporan');

Route::get('/home/rekapitulasi', 'PageController@rekapitulasi');
	// Routes for content of rekapitulasi
	//Route::get('/home/rekapitulasi/surat_tugas', 'PageController@rekapitulasi_surat');
	Route::get('/home/rekapitulasi/perjalanan', 'PageController@rekapitulasi_perjalanan');
	//Route::get('/home/rekapitulasi/keuangan', 'PageController@rekapitulasi_keuangan');

Route::get('/home/referensi', 'PageController@referensi');

Route::resource('home/referensi/pegawai', 'PenggunaUController');
Route::resource('home/surat_tugas', 'Surat_TugasUController');
Route::resource('home/laporan', 'LaporanUController');
Route::resource('home/rekapitulasi/surat_tugas', 'Rekap_SuratUController');
Route::resource('home/rekapitulasi/keuangan', 'Rekap_UangUController');
Route::resource('home/referensi/pangkat', 'PangkatUController');
Route::resource('home/referensi/jabatan', 'JabatanUController');
Route::resource('home/referensi/eselon', 'EselonUController');
Route::resource('home/referensi/hotel', 'HotelUController');
Route::resource('home/referensi/bidang', 'BidangUController');
Route::resource('home/referensi/wilayah', 'WilayahUController');
Route::resource('home/referensi/transportasi', 'TransportasiUController');
Route::resource('home/referensi/representasi', 'RepresentasiUController');
Route::resource('home/referensi/harian', 'HarianUController');
// Routes for process
Route::get('/home/surat_tugas/tambah_surat_form', 'HomeController@index');
// End routes for users --------
//form
Route::resource('pengguna', 'PenggunaController');
Route::resource('surat_tugas', 'Surat_TugasController');
Route::resource('surat_tugasU', 'Surat_TugasUController');
Route::resource('laporan', 'LaporanController');
Route::resource('laporanU', 'LaporanUController');
Route::resource('rekap_surat', 'Rekap_SuratController');
Route::resource('rekap_surat', 'Rekap_SuratUController');
Route::resource('rekap_uang', 'Rekap_UangController');
Route::resource('rekap_uang', 'Rekap_UangController');
Route::resource('pangkat', 'PangkatUController');
Route::resource('jabatan', 'JabatanUController');
Route::resource('eselon', 'EselonUController');
Route::resource('hotel', 'HotelUController');
Route::resource('wilayah', 'WilayahUController');
Route::resource('transportasi', 'TransportasiUController');
Route::resource('representasi', 'RepresentasiUController');
Route::resource('harian', 'HarianUController');
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/user/form/edit_laporan_form.blade.php
<!-- Modal -->
  <div class="modal fade" id="ubah_laporan" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title text-center">Ubah Laporan</h2>
        </div>
          <form action="{{route('laporanU.update', $l->kode_laporan)}}" method="POST">
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Kode SPPD :</label>
			    <input type="text" class="form-control" name="kode_SPPD" id="kode" value="{{$l->kode_SPPD}}" required>
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Total Biaya :</label>
			    <input type="text" class="form-control" name="biaya" id="biaya" placeholder="contoh : 100000" value="{{$l->biaya}}" required>
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="file">File :</label>
			    <input type="file" class="form-control" name="file" id="file">
			</div>
			</div>
			<div class="modal-footer">
          	<div class="col-lg-12 col-sm-12">
          		<input type="hidden" name="_method" value="put">
          		<input type="hidden" name="_token" value="{{ csrf_token() }}">
	        	<input type="submit" class="btn btn-primary" value="Ubah">
	          	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
        	</div>
		  </form>
      </div>
    </div>
  </div>

resources/views/user/form/edit_surat_form.blade.php
@extends('layout.user_app')

@section('title', 'Tetra | Ubah Surat Tugas')

@section('content')
<!-- Modal -->
        <div class="modal-header">
          <h2 class="modal-title text-center">Ubah Surat Tugas</h2>
          <form action="{{route('surat_tugasU.update', $s->kode_SPPD)}}" method="POST" enctype="multipart/form-data">
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Kode SPPD :</label>
			    <input type="text" class="form-control" name="kode_SPPD" id="kode_SPPD" value="{{$s->kode_SPPD}}" required>
			</div>
			</div>

          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Pemberian :</label>
				<input type="date" class="form-control" name="tgl_pemberian" id="tgl_pemberian" value="{{$s->tgl_pemberian}}" required>
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Mulai :</label>
				<input type="date" class="form-control" name="tgl_mulai" id="tgl_mulai" value="{{$s->tgl_mulai}}">
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Selesai :</label>
				<input type="date" class="form-control" name="tgl_selesai" id="tgl_selesai" value="{{$s->tgl_selesai}}">
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Lokasi Tujuan :</label>
			    <input type="text" class="form-control" name="lokasi" id="lokasi" value="{{$s->lokasi}}">
			</div>
			</div>

          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="file">File :</label>
			    <input type="file" class="form-control" name="file" id="file" accept="image/*">
			</div>
			</div>
		<div class="modal-footer">
          	<div class="col-lg-12 col-sm-12">
    			<!--<button id="add-more" name="add-more" class="navbar-left btn btn-primary">Tambah Anggota</button>-->
    			<input type="hidden" name="_method" value="put">
    			<input type="hidden" name="_token" value="{{ csrf_token() }}">
	        	<input type="submit" class="btn btn-primary" value="Ubah">
	          	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
        </div>
        </div>
		  </form>
		  <div class="container text-center">
		  <!--<img src="{{ asset('storage/upload/1.png')}}" alt=""> <!--dari ini-->
		  <img src="{{ asset('storage/upload/'.$s->file)}}" alt=""> <!--jadi kyk gini-->
		  </div>
 <!-- end of modal -->
@endsection
<script>
$(document).ready(function () {
    var next = 0;
    $("#add-more").click(function(e){
        e.preventDefault();
        var addto = "#field" + next;
        var addRemove = "#field" + (next);
        next = next + 1;
        var newIn = ' <div id="field'+ next +'" name="field'+ next +'"><!-- Text input--><div class="col-md-6 col-sm-6"> <div class="form-group"><input type="text" class="form-control" name="anggota'+ next +'" id="anggota"></div></div>';
        var newInput = $(newIn);
        var removeBtn = '<div class="col-md-6 col-sm-6"> <div class="form-group"><button id="remove' + (next - 1) + '" class="btn btn-danger remove-me navbar-right" >Remove</button></div></div><div id="field">';
        var removeButton = $(removeBtn);
        $(addto).after(newInput);
        $(addRemove).after(removeButton);
        $("#field" + next).attr('data-source',$(addto).attr('data-source'));
        $("#count").val(next);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
    });

});
 </script>
<!--
<form action="#">
	<div class="form-group">
	    <label for="text">Kode SPPD :</label>
	    <input type="text" class="form-control" id="kode">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Pemberian :</label>
		<input type="date" class="form-control" name="" id="tgl_pemberian">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Mulai :</label>
		<input type="date" class="form-control" name="" id="tgl_mulai">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Selesai :</label>
		<input type="date" class="form-control" name="" id="tgl_selesai">
	</div>
	<div class="form-group">
	    <label for="nbr">Lama Perjalanan (Hari) :</label>
	    <input type="number" class="form-control" id="lama_perjalanan">
	</div>
	<div class="form-group">
	    <label for="text">Tujuan :</label>
	    <input type="text" class="form-control" id="tujuan">
	</div>
	<label class="radio-inline"><input type="radio" name="optradio">Admin</label>
	<label class="radio-inline"><input type="radio" name="optradio">Pegawai</label>
	<br>
  	<button type="submit" class="btn btn-success">Submit</button>
  	<button type="submit" class="btn btn-danger">Reset</button>
</form>
-->
	

resources/views/user/form/tambah_laporan_form.blade.php
<!-- Modal -->
  <div class="modal fade" id="tambah_laporan" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title text-center">Tambah Laporan</h2>
        </div>
          <form action="{{ route('laporanU.store') }}" method="POST">
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Kode SPPD :</label>
			    <input type="text" class="form-control" name="kode_SPPD" id="kode" required>
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Total Biaya :</label>
			    <input type="text" class="form-control" name="biaya" id="biaya" placeholder="contoh : 100000" required>
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="file">File :</label>
			    <input type="file" class="form-control" name="file" id="file">
			</div>
			</div>
			<div class="modal-footer">
          	<div class="col-lg-12 col-sm-12">
          		<input type="hidden" name="_token" value="{{ csrf_token() }}">
	        	<input type="submit" class="btn btn-primary" value="Tambah">
	          	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
        	</div>
		  </form>
      </div>
    </div>
  </div>

resources/views/user/form/tambah_surat_form.blade.php
<!-- Modal -->
  <div class="modal fade" id="tambah_surat" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title text-center">Tambah Surat Tugas</h2>
        </div>
          <form action="{{ route('surat_tugasU.store') }}" method="POST" enctype="multipart/form-data">
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Kode SPPD :</label>
			    <input type="text" class="form-control" name="kode_SPPD" id="kode_SPPD">
			</div>
			</div>

          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Pemberian :</label>
				<input type="date" class="form-control" name="tgl_pemberian" id="tgl_pemberian">
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Mulai :</label>
				<input type="date" class="form-control" name="tgl_mulai" id="tgl_mulai">
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="date">Tanggal Selesai :</label>
				<input type="date" class="form-control" name="tgl_selesai" id="tgl_selesai">
			</div>
			</div>
			
          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">Lokasi Tujuan :</label>
			    <input type="text" class="form-control" name="lokasi" id="lokasi">
			</div>
			</div>

          	<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="file">File :</label>
			    <input type="file" class="form-control" name="file" id="file" accept="image/*" required>
			</div>
			</div>

			<!--<div id="field">
            <div id="field0">
			<div class="col-lg-6 col-sm-6">
			<div class="form-group">
			    <label for="text">NIP Anggota :</label>
			    <input type="text" class="form-control" name="anggota" id="anggota">
			</div>
			</div>
			</div>
			</div>-->
			<div class="modal-footer">
          	<div class="col-lg-12 col-sm-12">
    			<!--<button id="add-more" name="add-more" class="navbar-left btn btn-primary">Tambah Anggota</button>-->
    			<input type="hidden" name="_token" value="{{ csrf_token() }}">
	        	<input type="submit" class="btn btn-primary" value="Tambah">
	          	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
        </div>
		  </form>
      </div>
    </div>
  </div>
  <!-- end of modal -->
 <script>
$(document).ready(function () {
    var next = 0;
    $("#add-more").click(function(e){
        e.preventDefault();
        var addto = "#field" + next;
        var addRemove = "#field" + (next);
        next = next + 1;
        var newIn = ' <div id="field'+ next +'" name="field'+ next +'"><!-- Text input--><div class="col-md-6 col-sm-6"> <div class="form-group"><input type="text" class="form-control" name="anggota'+ next +'" id="anggota"></div></div>';
        var newInput = $(newIn);
        var removeBtn = '<div class="col-md-6 col-sm-6"> <div class="form-group"><button id="remove' + (next - 1) + '" class="btn btn-danger remove-me navbar-right" >Remove</button></div></div><div id="field">';
        var removeButton = $(removeBtn);
        $(addto).after(newInput);
        $(addRemove).after(removeButton);
        $("#field" + next).attr('data-source',$(addto).attr('data-source'));
        $("#count").val(next);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
    });

});
 </script>
<!--
<form action="#">
	<div class="form-group">
	    <label for="text">Kode SPPD :</label>
	    <input type="text" class="form-control" id="kode">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Pemberian :</label>
		<input type="date" class="form-control" name="" id="tgl_pemberian">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Mulai :</label>
		<input type="date" class="form-control" name="" id="tgl_mulai">
	</div>
	<div class="form-group">
	    <label for="date">Tanggal Selesai :</label>
		<input type="date" class="form-control" name="" id="tgl_selesai">
	</div>
	<div class="form-group">
	    <label for="nbr">Lama Perjalanan (Hari) :</label>
	    <input type="number" class="form-control" id="lama_perjalanan">
	</div>
	<div class="form-group">
	    <label for="text">Tujuan :</label>
	    <input type="text" class="form-control" id="tujuan">
	</div>
	<label class="radio-inline"><input type="radio" name="optradio">Admin</label>
	<label class="radio-inline"><input type="radio" name="optradio">Pegawai</label>
	<br>
  	<button type="submit" class="btn btn-success">Submit</button>
  	<button type="submit" class="btn btn-danger">Reset</button>
</form>
-->
	